fastlane_version '2.53.1'

before_all do
  #ensure_git_branch
  #ensure_git_status_clean
  #git_pull
end

platform :ios do
   # iOS Lanes
   desc 'Fetch certificates and provisioning profiles'
lane :certificates do
    #git_url("https://gitlab.com/tanduong/certificates.git")

  match(app_identifier: 'com.app.bundle', type: 'development', readonly: false)
  match(app_identifier: 'com.app.bundle', type: 'appstore', readonly: false)
end

desc 'Build the iOS application.'
private_lane :build do
  certificates
  increment_build_number(xcodeproj: './ios/name.xcodeproj')
  gym(scheme: 'name', project: './ios/name.xcodeproj')
end

desc 'Ship to Testflight.'
  lane :beta do
    build
    pilot
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/name.xcodeproj')
    push_to_git_remote
  end

end

platform :android do
  # Android Lanes
end